# Numpy Basics

In [1]:
import numpy as np
np.__version__

'1.11.1'

In [2]:
# Create a length-4 integer array filled with zeros
np.zeros(4
         , dtype=int)

array([0, 0, 0, 0])

In [3]:
# Create a 4*4 floating-point array filled with ones
np.ones((4, 4), dtype=float)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [4]:
# Create an array Starting at 0, ending at 40, stepping by 4
# (this is similar to the built-in range() function)
np.arange(0, 40, 4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [5]:
# Create an array of five values evenly spaced between 0 and 4
np.linspace(0, 4, 5)

array([ 0.,  1.,  2.,  3.,  4.])